services:
  nginx:
    image: nginx:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nodebb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/selfsigned.crt:/etc/nginx/caiz.crt:ro
      - ./nginx/selfsigned.key:/etc/nginx/cai.key:ro
  nodebb:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '4567:4567'
    volumes:
      - ./plugins:/usr/src/plugins
      - ./app:/usr/src/app
    command: ['nodebb', 'start']
