services:
  nginx:
    env_file:
      - .dev.env
    volumes:
      - ./nginx/caiz.test+3.pem:/etc/nginx/caiz.crt:ro
      - ./nginx/caiz.test+3-key.pem:/etc/nginx/caiz.key:ro
  nodebb:
    env_file:
      - .dev.env
    command: ['nodebb', 'dev']
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: postgres:17.4-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  elasticsearch:
    build: ./elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # Development-friendly disk watermarks (absolute thresholds)
      - cluster.routing.allocation.disk.watermark.low=5gb
      - cluster.routing.allocation.disk.watermark.high=2gb
      - cluster.routing.allocation.disk.watermark.flood_stage=1gb
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/postgresql/data
  esdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/elasticsearch/data
