services:
  nginx:
    env_file:
      - .dev.env
  nodebb:
    env_file:
      - .dev.env
    command: ['nodebb', 'dev']
    depends_on:
      - postgres
  postgres:
    image: postgres:17.4-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/postgresql/data
