services:
  nginx:
    image: nginx:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nodebb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/selfsigned.crt:/etc/nginx/caiz.crt:ro
      - ./nginx/selfsigned.key:/etc/nginx/caiz.key:ro
  nodebb:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '4567:4567'
    volumes:
      - ./plugins:/usr/src/plugins
      - ./app:/usr/src/app
    command: bash -lc " ./nodebb build && node loader.js --no-daemon"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/elasticsearch/data
